<script setup>
import { computed, ref } from 'vue';
import { useRouter } from 'vue-router';
import { signOut } from '../services/cloudSync';
import { chooseGuest, clearIdentity, identity } from '../services/identity';
import { useLearningStore } from '../stores/learning';
const router = useRouter();
const { audio, cloudSync, progressSummary, syncWithCloud, updateAudio, previewKeySound, previewWordSound, previewAnswerSound, clearLocalProgress } = useLearningStore();
const busy = ref(false); const message = ref('');
const syncLabel = computed(() => ({ idle: '等待同步', syncing: '正在同步…', synced: '已同步', offline: '离线，记录已保存在本机', error: '同步失败' }[cloudSync.status]));
const lastSync = computed(() => cloudSync.lastSyncedAt ? new Date(cloudSync.lastSyncedAt).toLocaleString('zh-CN') : '暂无');
async function syncNow() { busy.value = true; message.value = ''; try { await syncWithCloud(); message.value = '本机和云端进度已合并。'; } catch (error) { message.value = error.message || '同步失败'; } finally { busy.value = false; } }
async function logOut(keepLocal) { busy.value = true; try { if (identity.isAccount.value) await signOut(); if (keepLocal) { await chooseGuest(); await router.replace({ name: 'home' }); } else { await clearLocalProgress(); await clearIdentity(); await router.replace({ name: 'auth' }); } } finally { busy.value = false; } }
async function openLogin() { await clearIdentity(); await router.push({ name: 'auth' }); }
function confirmClear() { if (window.confirm('确定清除这台设备上的学习记录吗？云端记录不会删除。')) void clearLocalProgress(); }
</script>
<template>
  <main class="shell"><section class="view active">
    <header class="hero account-heading"><p class="eyebrow">MY SPACE</p><h1>我的</h1><p>学习记录、偏好和账号，都在这里。</p></header>
    <div class="card account-card"><div class="account-identity"><span class="avatar">{{ identity.isGuest.value ? '游' : (identity.user.value?.email?.[0] || '用').toUpperCase() }}</span><div><strong>{{ identity.label.value }}</strong><small>{{ identity.isGuest.value ? '记录仅保存在这台设备' : '已连接 Supabase 云端' }}</small></div></div><div class="account-stats"><div><b>{{ progressSummary.learnedDays }}</b><span>已学天数</span></div><div><b>{{ progressSummary.practicedWords }}</b><span>练习单词</span></div><div><b>{{ progressSummary.wrongWords }}</b><span>错词</span></div></div><template v-if="identity.isGuest.value"><div class="sync-panel"><strong>换手机也保留进度</strong><p>登录后当前游客记录会自动合并到云端。</p><button class="primary full-button" @click="openLogin">登录 / 创建账号</button></div></template><template v-else><div class="sync-panel"><div class="sync-row"><span>同步状态</span><strong :class="`status-${cloudSync.status}`">{{ syncLabel }}</strong></div><div class="sync-row"><span>最后同步</span><strong>{{ lastSync }}</strong></div><button class="primary full-button" :disabled="busy || cloudSync.status === 'syncing'" @click="syncNow">立即同步</button><p v-if="message" class="hint">{{ message }}</p></div></template></div>
    <section class="settings-section"><h2>学习工具</h2><div class="menu-list"><button class="menu-item" @click="router.push({ name: 'wrongbook' })"><span>错词本<small>复习答错过的单词</small></span><b>›</b></button><button class="menu-item" @click="router.push({ name: 'statistics' })"><span>学习统计<small>查看进度、正确率和累计练习</small></span><b>›</b></button></div></section>
    <section class="settings-section"><h2>音频设置</h2><div class="audio-setting account-audio"><label><input v-model="audio.auto" type="checkbox" @change="updateAudio"> 自动播放单词</label><label>发音<select v-model="audio.accent" @change="updateAudio"><option value="us">美式</option><option value="uk">英式</option></select><button class="mini-audio-button" type="button" @click="previewWordSound">试听</button></label><label class="range-setting">单词音量 <input v-model.number="audio.wordVolume" type="range" min="0" max="100" step="5" @change="updateAudio"><output>{{ audio.wordVolume }}%</output></label><label><input v-model="audio.keyboard" type="checkbox" @change="updateAudio"> 沉浸式键盘音效</label><label v-if="audio.keyboard">键盘声音<select v-model="audio.keyboardSound" @change="updateAudio"><option value="机械键盘">机械键盘（随机）</option><option value="机械键盘1">机械键盘 1</option><option value="机械键盘2">机械键盘 2</option><option value="老式机械键盘">老式机械键盘</option><option value="笔记本键盘">笔记本键盘</option></select><button class="mini-audio-button" type="button" @click="previewKeySound">试听</button></label><label v-if="audio.keyboard" class="range-setting">键盘音量 <input v-model.number="audio.keyboardVolume" type="range" min="0" max="100" step="5" @change="updateAudio"><output>{{ audio.keyboardVolume }}%</output></label><label><input v-model="audio.feedback" type="checkbox" @change="updateAudio"> 答题反馈音</label><label v-if="audio.feedback" class="range-setting">反馈音量 <input v-model.number="audio.feedbackVolume" type="range" min="0" max="100" step="5" @change="updateAudio"><output>{{ audio.feedbackVolume }}%</output></label><div class="audio-preview-row"><button class="mini-audio-button" type="button" @click="previewAnswerSound('correct')">试听答对</button><button class="mini-audio-button" type="button" @click="previewAnswerSound('wrong')">试听答错</button></div><span>拼写训练输入字母时播放键盘声，答对和答错播放反馈音。</span></div></section>
    <section class="settings-section"><h2>应用</h2><div class="menu-list"><button class="menu-item" @click="router.push({ name: 'home' })"><span>安装到手机<small>从浏览器添加到主屏幕</small></span><b>›</b></button><button class="menu-item" @click="confirmClear"><span>清理本机数据<small>只清理当前设备，不影响云端</small></span><b class="danger-text">清理</b></button></div></section>
    <div v-if="!identity.isGuest.value" class="logout-actions"><button class="secondary" :disabled="busy" @click="logOut(true)">退出账号，保留本机记录</button><button class="danger-button" :disabled="busy" @click="logOut(false)">退出并清除本机记录</button></div>
  </section></main>
</template>
