<script setup>
import { computed, onMounted, ref } from 'vue';
import { getAudioSettings, playWord, saveAudioSettings } from './services/audio';

const days = window.CET4_DAYS || [];
const REVIEW_DAYS = [1, 2, 4, 7, 15, 30];
const KEY = 'cet4-progress-v1';
const progress = ref(JSON.parse(localStorage.getItem(KEY) || '{"words":{},"days":{},"daySchedule":{}}'));
progress.value.daySchedule ||= {};
const view = ref('home');
const selectedDay = ref(null), reviewGap = ref(null), customWords = ref(null), sessionLabel = ref('');
const mode = ref('mixed'), count = ref(20), queue = ref([]), index = ref(0), current = ref(null), questionType = ref('choice');
const answered = ref(false), attempts = ref(0), right = ref(0), wrong = ref(0), mistakes = ref({}), typed = ref(''), feedback = ref('');
const audio = ref(getAudioSettings()), installPrompt = ref(null);
const dayInfo = computed(() => days.find(d => d.day === selectedDay.value));
const wrongWords = computed(() => { const map = new Map(); days.forEach(day => day.words.forEach(word => { const p = progress.value.words[word.word.toLowerCase()]; if (p?.inWrongBook && !map.has(word.word.toLowerCase())) map.set(word.word.toLowerCase(), word); })); return [...map.values()]; });
const sessionMistakes = computed(() => [...new Map(queue.value.filter(w => mistakes.value[w.word.toLowerCase()]).map(w => [w.word.toLowerCase(), w])).values()]);
const nextNewDay = computed(() => days.find(day => !progress.value.daySchedule[day.day]));
const dueReviews = computed(() => { const now = today(); return days.flatMap(day => { const s = progress.value.daySchedule[day.day]; if (!s) return []; s.reviewed ||= []; const elapsed = daysBetween(s.learnedDate, now); const gap = REVIEW_DAYS.find(v => v <= elapsed && !s.reviewed.includes(v)); return gap ? [{ day: day.day, gap, overdue: elapsed > gap }] : []; }); });

function today() { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`; }
function daysBetween(a, b) { return Math.floor((new Date(`${b}T12:00:00`) - new Date(`${a}T12:00:00`)) / 86400000); }
function save() { localStorage.setItem(KEY, JSON.stringify(progress.value)); }
function meta(word) { const key = word.word.toLowerCase(); progress.value.words[key] ||= { right: 0, wrong: 0 }; return progress.value.words[key]; }
function speak(word) { playWord(word.word, audio.value.accent); }
function updateAudio() { saveAudioSettings(audio.value); }
function shuffle(list) { const copy = [...list]; for (let i = copy.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [copy[i], copy[j]] = [copy[j], copy[i]]; } return copy; }
function show(next) { view.value = next; window.scrollTo(0, 0); }
function openDay(day, gap = null) { selectedDay.value = day; reviewGap.value = gap; customWords.value = null; sessionLabel.value = `Day ${day}`; show('setup'); }
function openCustom(words, label) { selectedDay.value = null; reviewGap.value = null; customWords.value = words; sessionLabel.value = label; show('setup'); }
function sourceWords() { return customWords.value || dayInfo.value?.words || []; }
function start(nextMode = mode.value, custom = null) { mode.value = nextMode; const source = custom || sourceWords(); queue.value = shuffle(source).slice(0, custom || customWords.value ? source.length : Number(count.value)); index.value = right.value = wrong.value = attempts.value = 0; mistakes.value = {}; show('quiz'); nextQuestion(); }
function nextQuestion() { if (index.value >= queue.value.length) return finish(); current.value = queue.value[index.value]; attempts.value = 0; answered.value = false; typed.value = ''; feedback.value = ''; questionType.value = mode.value === 'mixed' ? (Math.random() < .5 ? 'spell' : 'choice') : mode.value; if (audio.value.auto) speak(current.value); }
function choices() { const source = selectedDay.value ? dayInfo.value.words : days.flatMap(d => d.words); return shuffle([current.value, ...shuffle(source.filter(w => w.word !== current.value.word && w.meaning !== current.value.meaning)).slice(0, 3)]); }
function recordWrong() { const p = meta(current.value), key = current.value.word.toLowerCase(); wrong.value++; p.wrong++; p.inWrongBook = true; p.wrongReviewCount = 0; p.lastWrong = today(); if (selectedDay.value) p.wrongDay = selectedDay.value; mistakes.value[key] = (mistakes.value[key] || 0) + 1; save(); }
function answer(ok) { if (answered.value) return; if (!ok) { attempts.value++; recordWrong(); if (attempts.value < 3) { feedback.value = `回答不对，还可以尝试 ${3 - attempts.value} 次。`; return; } } else { right.value++; const p = meta(current.value); p.right++; p.lastRight = today(); if (customWords.value && p.inWrongBook && attempts.value === 0) { p.wrongReviewCount = (p.wrongReviewCount || 0) + 1; if (p.wrongReviewCount >= 3) p.inWrongBook = false; } save(); } answered.value = true; feedback.value = ok ? `正确：${current.value.word}` : `正确答案：${current.value.word} · ${current.value.meaning}`; }
function finish() { if (selectedDay.value) { const s = progress.value.daySchedule[selectedDay.value] ||= { learnedDate: today(), reviewed: [] }; if (reviewGap.value) s.reviewed = [...new Set([...(s.reviewed || []), ...REVIEW_DAYS.filter(x => x <= reviewGap.value)])]; else progress.value.days[selectedDay.value] = (progress.value.days[selectedDay.value] || 0) + 1; } save(); show('summary'); }
function next() { index.value++; nextQuestion(); }
function installVisible() { return !!installPrompt.value && !window.matchMedia?.('(display-mode: standalone)').matches; }
async function install() { if (!installPrompt.value) return; installPrompt.value.prompt(); await installPrompt.value.userChoice; installPrompt.value = null; }
onMounted(() => { window.addEventListener('beforeinstallprompt', e => { e.preventDefault(); installPrompt.value = e; }); window.addEventListener('appinstalled', () => { installPrompt.value = null; }); });
</script>

<template>
  <main class="shell">
    <section v-if="view==='home'" class="view active"><button v-if="installVisible()" class="install-app" @click="install">⬇ 安装到手机</button><header class="hero"><p class="eyebrow">CET-4 · 45天词汇</p><h1>今天背哪一天？</h1><p>把今天的 20 个词，变成明天的底气。</p></header><div class="home-actions"><button class="primary" @click="show('daily')">领取今日任务</button><button class="secondary" @click="show('wrongbook')">错词本 {{ wrongWords.length }}</button></div><div class="audio-setting"><label><input v-model="audio.auto" type="checkbox" @change="updateAudio"> 自动播放</label><label>声音<select v-model="audio.accent" @change="updateAudio"><option value="us">美式</option><option value="uk">英式</option></select></label><span>固定音频缺失时使用手机发音</span></div><div class="day-grid"><button v-for="day in days" :key="day.day" class="day" :class="{done:progress.days[day.day]}" @click="openDay(day.day)">Day {{ day.day }}<small>{{ day.count }}词</small></button></div></section>
    <section v-else-if="view==='daily'" class="view active"><button class="back" @click="show('home')">← 返回45天</button><header class="hero"><p class="eyebrow">EBBINGHAUS REVIEW</p><h1>今日任务</h1><p>{{ today() }}</p></header><div class="card"><div class="task-block"><h3 class="task-title">今日要背的单词</h3><div class="day-grid"><button v-if="nextNewDay" class="day" @click="openDay(nextNewDay.day)">Day {{ nextNewDay.day }}<small>{{ nextNewDay.count }}词</small></button></div><p v-if="!nextNewDay" class="hint">45天新词已经全部完成。</p></div><div class="task-block"><h3 class="task-title">要复习的单词</h3><div class="day-grid"><button v-for="item in dueReviews" :key="item.day" class="day" @click="openDay(item.day,item.gap)">Day {{ item.day }}<small>{{ item.overdue?'补第':'第' }}{{ item.gap }}天</small></button><button v-if="wrongWords.length" class="day" @click="openCustom(wrongWords,'今日错词')">错词<small>{{ wrongWords.length }}词</small></button></div><p v-if="!dueReviews.length&&!wrongWords.length" class="hint">今天暂无到期复习。</p></div></div></section>
    <section v-else-if="view==='setup'" class="view active"><button class="back" @click="show('home')">← 返回45天</button><div class="card setup-card"><p class="eyebrow">{{ sessionLabel }} · {{ sourceWords().length }}词</p><h2>选择抽背方式</h2><button class="mode" @click="start('choice')"><b>英译中</b><span>看英文，选择中文释义</span></button><button class="mode" @click="start('spell')"><b>中译英</b><span>看中文，输入英文拼写</span></button><button class="mode" @click="start('mixed')"><b>混合训练</b><span>两种题型随机出现</span></button><label v-if="!customWords" class="count-label">本轮题数<select v-model="count"><option>10</option><option>20</option><option>30</option><option>50</option></select></label><div class="task-block"><h3 class="task-title">本组单词</h3><div class="word-list"><div v-for="(word,i) in sourceWords()" :key="word.word+i" class="word-row"><div class="word-en"><b>{{ i+1 }}. {{ word.word }}</b><button class="speak-btn" @click="speak(word)">🔊</button><div class="review-note">{{ word.pos }} · {{ word.ipa }}</div></div><div class="meaning-cover revealed">{{ word.meaning }}</div></div></div></div></div></section>
    <section v-else-if="view==='quiz'&&current" class="view active"><div class="quiz-top"><button class="back" @click="show('setup')">× 退出</button><span>{{ sessionLabel }}</span><span>{{ index+1 }}/{{ queue.length }}</span></div><div class="progress"><i :style="{width:`${index/Math.max(1,queue.length)*100}%`}"></i></div><article class="card question-card"><p class="eyebrow">{{ questionType==='spell'?'中译英（3次机会）':'英译中（3次机会）' }}</p><h2><span class="prompt-line">{{ questionType==='spell'?current.meaning:current.word }} <button class="speak-btn" @click="speak(current)">🔊</button></span></h2><p class="hint"><span class="quiz-ipa">{{ current.ipa }}</span><span class="quiz-pos">{{ current.pos }}</span></p><form v-if="questionType==='spell'" class="answer-area" @submit.prevent="answer(typed.trim().toLowerCase()===current.word.toLowerCase())"><input v-model="typed" autofocus autocomplete="off" placeholder="输入英文单词"><button class="primary">确认</button></form><div v-else class="choices"><button v-for="word in choices()" :key="word.word" class="choice" :disabled="answered" @click="answer(word.word===current.word)">{{ word.meaning }}</button></div><div v-if="feedback" class="feedback" :class="answered&&feedback.startsWith('正确')?'good':'bad'">{{ feedback }}</div><button v-if="answered" class="primary" @click="next">下一题</button></article></section>
    <section v-else-if="view==='wrongbook'" class="view active"><button class="back" @click="show('home')">← 返回45天</button><header class="hero"><p class="eyebrow">MISTAKE BOOK</p><h1>错词本</h1><p>连续正确复习 3 次后移出。</p></header><div class="word-list"><div v-for="word in wrongWords" :key="word.word" class="word-row"><div class="word-en"><b>{{ word.word }}</b><button class="speak-btn" @click="speak(word)">🔊</button><div class="review-note">正确复习 {{ meta(word).wrongReviewCount||0 }}/3</div></div><div class="meaning-cover revealed">{{ word.meaning }}</div></div></div><p v-if="!wrongWords.length" class="card hint">错词本还是空的。</p><button v-if="wrongWords.length" class="primary full-button" @click="openCustom(wrongWords,'错词复习')">开始复习错词</button></section>
    <section v-else class="view active"><div class="card summary-card"><p class="eyebrow">本轮完成</p><h2>{{ sessionLabel }} 训练总结</h2><div class="stats"><div><b>{{ right }}</b><span>答对</span></div><div><b>{{ wrong }}</b><span>答错</span></div><div><b>{{ Math.round(right/Math.max(1,right+wrong)*100) }}%</b><span>正确率</span></div></div><h3>本轮错词</h3><div class="mistakes"><div v-for="word in sessionMistakes" :key="word.word" class="mistake"><b>{{ word.word }}</b><span>{{ word.meaning }} · 错{{ mistakes[word.word.toLowerCase()] }}次</span></div><p v-if="!sessionMistakes.length">本轮全对，很稳！</p></div><button v-if="sessionMistakes.length" class="primary" @click="start('mixed',sessionMistakes)">只练本轮错词</button><button class="secondary" @click="show('home')">返回首页</button></div></section>
  </main>
</template>
