const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='cet4-progress-v1';
let progress=JSON.parse(localStorage.getItem(KEY)||'{"words":{},"days":{}}');
let state={day:null,mode:'mixed',queue:[],index:0,right:0,wrong:0,mistakes:{},current:null,answered:false,attempts:0};
let allMeaningsOpen=false;
const REVIEW_DAYS=[1,2,4,7,15,30];
const QUOTES=[
'前路浩浩荡荡，万事尽可期待。','努力的意义，在于让自己有选择权。','不必追光，你我皆是星辰。','那些看似不起波澜的日复一日，终会在某天让你看到坚持的意义。','半山腰总是最挤的，你得去山顶看看。','关关难过关关过，前路漫漫亦灿灿。','所有幸运，都是努力埋下的伏笔。','你现在的沉淀，都是未来惊喜的铺垫。','别怕路长，一步一步走总会抵达。','不驰于空想，不骛于虚声。',
'纵有狂风拔地起，我亦乘风破万里。','熬过无人问津的日子，才能拥抱诗和远方。','人生没有白走的路，每一步都算数。','与其仰望星空，不如亲手摘星。','别让懒惰，消耗你的野心。','暂时的低谷，是为了更高的起跳。','追风赶月莫停留，平芜尽处是春山。','坚持很难，但放弃会更遗憾。','你的目标，不该只停留在想象。','慢慢来，好戏都在烟火里。',
'凡心所向，素履以往。','与其抱怨黑暗，不如提灯前行。','每一次咬牙坚持，都是在积蓄力量。','生活原本沉闷，但跑起来就有风。','不必和别人比，只和过去的自己较量。','星光不问赶路人，时光不负有心人。','跌倒了就站起来，不必原地停留。','凡是过往，皆为序章。','心有丘壑，眼存山河。','努力不是一时热血，而是长久自律。',
'不惧前路未知，只怕止步不前。','厚积薄发，静候花开。','命运不会辜负每一个用力奔跑的人。','把困难当作台阶，而不是绊脚石。','愿你历尽千帆，归来仍是少年。','沉下心打磨自己，时间会给出答案。','人生最好的状态，是持续向上。','不要因为暂时失利，否定全部的自己。','道阻且长，行则将至；行而不辍，未来可期。','保持热爱，奔赴山海。',
'所有光芒，都需要时间才能被看见。','平凡的日子里，也可以活得热烈。','越努力，越幸运。','哪怕微光，亦可照亮前路。','停止内耗，专注当下。','心有所期，全力以赴，定有所成。','不怕万人阻挡，只怕自己投降。','耕耘当下，收获来日。','且将新火试新茶，诗酒趁年华。','你想要的生活，只能靠自己争取。'];
const views=['home','daily','wrongbook','setup','quiz','summary'];
function show(id){views.forEach(v=>$('#'+v).classList.toggle('active',v===id));scrollTo(0,0)}
function save(){localStorage.setItem(KEY,JSON.stringify(progress));updateWrongCount()}
function key(w){return w.word.toLowerCase()}
function today(){return new Date().toISOString().slice(0,10)}
function addDays(date,n){const d=new Date(date+'T12:00:00');d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)}
function wordMeta(w){const k=key(w);progress.words[k]||={right:0,wrong:0};return progress.words[k]}
function touchWord(w){const p=wordMeta(w),t=today();if(!p.firstSeen){p.firstSeen=t;p.reviewStep=0;p.nextReview=addDays(t,REVIEW_DAYS[0])}p.lastSeen=t;return p}
function setDailyQuote(){const t=today();let q=JSON.parse(localStorage.getItem('cet4-daily-quote')||'null');if(!q||q.date!==t){q={date:t,index:Math.floor(Math.random()*QUOTES.length)};localStorage.setItem('cet4-daily-quote',JSON.stringify(q))}$('#heroQuote').textContent=QUOTES[q.index]}
function shuffle(a){for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function editDistance(a,b){a=a.toLowerCase();b=b.toLowerCase();const d=Array.from({length:a.length+1},()=>[]);for(let i=0;i<=a.length;i++)d[i][0]=i;for(let j=0;j<=b.length;j++)d[0][j]=j;for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++)d[i][j]=Math.min(d[i-1][j]+1,d[i][j-1]+1,d[i-1][j-1]+(a[i-1]!==b[j-1]));return d[a.length][b.length]}
function tokens(s){return new Set(s.replace(/[；，、,.；]/g,' ').split(/\s+/).filter(x=>x.length>1))}
function similarity(a,b){const A=tokens(a.meaning),B=tokens(b.meaning);let common=0;A.forEach(x=>{if(B.has(x))common++});const semantic=common/Math.max(1,new Set([...A,...B]).size);const spelling=1-editDistance(a.word,b.word)/Math.max(a.word.length,b.word.length);return semantic*2+spelling+(a.pos===b.pos?.25:0)+Math.random()*.12}
function dayData(n){return CET4_DAYS[n-1]}
function renderDays(){const g=$('#dayGrid');g.innerHTML='';CET4_DAYS.forEach(d=>{const b=document.createElement('button');b.className='day'+(progress.days[d.day]?' done':'');b.innerHTML=`Day ${d.day}<small>${d.count}词</small>`;b.onclick=()=>openDay(d.day);g.appendChild(b)});updateWrongCount()}
function updateWrongCount(){const n=Object.values(progress.words).filter(x=>x.inWrongBook||(x.wrong>x.right&&!('inWrongBook'in x))).length;$('#wrongCount').textContent=n}
function renderSetupWords(words){const box=$('#setupWordList');box.innerHTML='';words.forEach((w,i)=>{const row=document.createElement('div');row.className='word-row';row.innerHTML=`<div class="word-en">${i+1}. ${w.word}<div class="review-note">${w.pos} ${w.ipa}</div></div><div class="meaning-cover revealed">${w.meaning}</div>`;box.appendChild(row)})}
function openDay(day,reviewGap=null){state.day=day;state.reviewGap=reviewGap;state.customWords=null;state.wrongReview=!!reviewGap;$('#setupDay').textContent=`DAY ${day} · ${dayData(day).count}词${reviewGap?` · 第${reviewGap}天复习`:''}`;renderSetupWords(dayData(day).words);show('setup')}
function openWrongReview(words,label='今日错词'){state.day=label;state.reviewGap=null;state.customWords=words;state.wrongReview=true;$('#setupDay').textContent=`${label} · ${words.length}词 · 正确复习3次后移出错词本`;renderSetupWords(words);show('setup')}
function weightedPool(words){const out=[];words.forEach(w=>{const p=progress.words[key(w)]||{wrong:0,right:0};const weight=1+Math.min(4,Math.max(0,p.wrong-p.right));for(let i=0;i<weight;i++)out.push(w)});return out}
function start(mode,custom){state.mode=mode;const count=custom?.length||Number($('#questionCount').value);const source=custom||dayData(state.day).words;if(custom){state.queue=shuffle([...custom])}else if(mode==='spell'){state.queue=source.slice(0,count)}else{const pool=weightedPool(source);state.queue=[];while(state.queue.length<count)state.queue.push(...shuffle([...pool]));state.queue=state.queue.slice(0,count)}Object.assign(state,{index:0,right:0,wrong:0,mistakes:{},answered:false,attempts:0});show('quiz');nextQuestion()}
function nextQuestion(){if(state.index>=state.queue.length)return finish();state.current=state.queue[state.index];state.answered=false;state.attempts=0;$('#feedback').className='feedback hidden';$('#next').classList.add('hidden');$('#progressText').textContent=`${state.index+1}/${state.queue.length}`;$('#progressBar').style.width=`${state.index/state.queue.length*100}%`;$('#quizLabel').textContent=`Day ${state.day}`;let type=state.mode==='mixed'?(Math.random()<.5?'spell':'choice'):state.mode;state.type=type;if(type==='spell')renderSpell();else renderChoice()}
function renderSpell(){const w=state.current;$('#promptLabel').textContent='中译英（按词表顺序，3次机会）';$('#prompt').textContent=w.meaning;$('#hint').textContent=`${w.pos}  ${w.ipa}`;$('#choices').classList.add('hidden');$('#spellForm').classList.remove('hidden');$('#spellInput').value='';$('#spellInput').style.borderColor='';$('#spellInput').classList.remove('correct','wrong');setTimeout(()=>$('#spellInput').focus(),100)}
function distractors(word){const source=Number.isInteger(state.day)?dayData(state.day).words:CET4_DAYS.flatMap(d=>d.words);const same=source.filter(w=>w!==word&&w.meaning!==word.meaning);return same.sort((a,b)=>similarity(word,b)-similarity(word,a)).slice(0,3)}
function renderChoice(){const w=state.current;$('#promptLabel').textContent='英译中（3次机会）';$('#prompt').textContent=w.word;$('#hint').textContent=`${w.pos}  ${w.ipa}`;$('#spellForm').classList.add('hidden');const box=$('#choices');box.classList.remove('hidden');box.innerHTML='';shuffle([w,...distractors(w)]).forEach((x,i)=>{const b=document.createElement('button');b.className='choice';b.innerHTML=`<b>${'ABCD'[i]}.</b> ${x.meaning}`;b.onclick=()=>chooseAnswer(x===w,b,x);b.dataset.correct=x===w;box.appendChild(b)})}
function recordWrong(){const w=state.current,k=key(w),p=touchWord(w);state.wrong++;p.wrong++;p.lastWrong=today();p.wrongPending=true;p.inWrongBook=true;p.wrongReviewCount=0;if(Number.isInteger(state.day))p.wrongDay=state.day;p.nextReview=addDays(today(),1);state.mistakes[k]=(state.mistakes[k]||0)+1;if(state.queue.length<100)state.queue.splice(Math.min(state.queue.length,state.index+3+Math.floor(Math.random()*5)),0,w);save()}
function completeAnswer(ok){state.answered=true;const w=state.current,k=key(w),p=touchWord(w);if(ok){state.right++;p.right++;p.lastRight=today();if(state.wrongReview&&p.inWrongBook&&state.attempts===0){p.wrongReviewCount=(p.wrongReviewCount||0)+1;if(p.wrongReviewCount>=3){p.inWrongBook=false;p.wrongPending=false}}else if(p.inWrongBook&&state.attempts>0){p.wrongReviewCount=0}if(state.attempts>0)p.nextReview=addDays(today(),1);else if(!p.nextReview){p.reviewStep=0;p.nextReview=addDays(today(),REVIEW_DAYS[0])}save()}if(state.type==='choice')$$('.choice').forEach(b=>{b.disabled=true;if(b.dataset.correct==='true')b.classList.add('correct')});else if(ok)$('#spellInput').style.borderColor='#27845f';const f=$('#feedback');f.className='feedback '+(ok?'good':'bad');const reviewTip=ok&&state.wrongReview&&p.inWrongBook?`<br>错词复习进度：${p.wrongReviewCount||0}/3`:ok&&state.wrongReview&&!p.inWrongBook?'<br>已连续复习正确3次，移出错词本。':'';f.innerHTML=ok?`正确：<b>${w.word}</b>${reviewTip}`:`3次机会已用完。正确答案：<b>${w.word}</b><br>${w.meaning}`;$('#next').classList.remove('hidden')}
function chooseAnswer(ok,button,chosen){if(state.answered||button.disabled)return;if(ok)return completeAnswer(true);button.classList.add('wrong');button.disabled=true;const word=document.createElement('span');word.style.cssText='float:right;margin-left:12px;font-weight:800;color:#c54343';word.textContent=chosen.word;button.appendChild(word);state.attempts++;recordWrong();const left=3-state.attempts;if(left>0){const f=$('#feedback');f.className='feedback bad';f.textContent=`这个选项不对，还可以选择 ${left} 次。`}else completeAnswer(false)}
function esc(s){return s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
function spellingDiff(typed,target){let html='';const n=Math.max(typed.length,target.length);for(let i=0;i<n;i++){const a=typed[i],b=target[i];if(a&&b&&a.toLowerCase()===b.toLowerCase())html+=`<span style="color:#27845f;font-weight:800">${esc(a)}</span>`;else if(a)html+=`<span style="color:#c54343;font-weight:800;text-decoration:underline">${esc(a)}</span>`;else html+='<span style="color:#c54343;font-weight:900">-</span>'}return html}
$('#spellForm').onsubmit=e=>{e.preventDefault();if(state.answered)return;const input=$('#spellInput'),typed=input.value.trim(),target=state.current.word;if(typed.toLowerCase()===target.toLowerCase())return completeAnswer(true);state.attempts++;recordWrong();const left=3-state.attempts,f=$('#feedback');f.className='feedback bad';f.innerHTML=`第 ${state.attempts} 次拼写：<span style="font-size:20px;letter-spacing:2px">${spellingDiff(typed,target)}</span><br>${left?`还有 ${left} 次机会；红色字母是错误位置，红色 - 表示遗漏字母。`:`3次机会已用完。正确答案：<b>${target}</b>`}`;input.value='';if(left)input.focus();else{state.answered=true;$('#next').classList.remove('hidden')}};
$('#next').onclick=()=>{state.index++;nextQuestion()};
function finish(){if(Number.isInteger(state.day)){progress.daySchedule||={};if(state.reviewGap){const s=progress.daySchedule[state.day];if(s){s.reviewed||=[];s.reviewed=[...new Set([...s.reviewed,...REVIEW_DAYS.filter(x=>x<=state.reviewGap)])];s.lastReview=today()}}else{progress.days[state.day]=(progress.days[state.day]||0)+1;progress.daySchedule[state.day]||={learnedDate:today(),reviewed:[]};progress.daySchedule[state.day].lastStudy=today()}}save();$('#progressBar').style.width='100%';$('#summaryTitle').textContent=`${Number.isInteger(state.day)?'Day '+state.day:state.day} 训练总结`;$('#rightStat').textContent=state.right;$('#wrongStat').textContent=state.wrong;const total=state.right+state.wrong;$('#rateStat').textContent=Math.round(state.right/Math.max(1,total)*100)+'%';const list=$('#mistakeList');list.innerHTML='';const source=Number.isInteger(state.day)?dayData(state.day).words:state.queue;const wrongWords=[...new Map(source.filter(w=>state.mistakes[key(w)]).map(w=>[key(w),w])).values()];wrongWords.forEach(w=>{const d=document.createElement('div');d.className='mistake';d.innerHTML=`<b>${w.word}</b><span>${w.meaning} · 错${state.mistakes[key(w)]}次</span>`;list.appendChild(d)});if(!wrongWords.length)list.innerHTML='<p>本轮全对，很稳！</p>';$('#retryWrong').classList.toggle('hidden',!wrongWords.length);$('#retryWrong').onclick=()=>start('mixed',wrongWords);show('summary');renderDays()}
function daysBetween(a,b){return Math.floor((new Date(b+'T12:00:00')-new Date(a+'T12:00:00'))/86400000)}
function dailyTask(){const t=today();progress.daySchedule||={};Object.keys(progress.days||{}).forEach(n=>{if(!progress.daySchedule[n])progress.daySchedule[n]={learnedDate:addDays(t,-1),lastStudy:addDays(t,-1),reviewed:[]}});const nextDay=CET4_DAYS.find(d=>!progress.daySchedule[d.day]),newBox=$('#todayNew');newBox.innerHTML='';if(nextDay){const b=document.createElement('button');b.className='day';b.innerHTML=`Day ${nextDay.day}<small>${nextDay.count}词</small>`;b.onclick=()=>openDay(nextDay.day);newBox.appendChild(b)}$('#newEmpty').classList.toggle('hidden',!!nextDay);const due=[];for(let day=1;day<=45;day++){const s=progress.daySchedule[day];if(!s)continue;s.reviewed||=[];const elapsed=daysBetween(s.learnedDate,t),pending=REVIEW_DAYS.filter(x=>x<=elapsed&&!s.reviewed.includes(x));if(pending.length)due.push({day,gap:pending[0],overdue:elapsed>pending[0]})}const dueSet=new Set(due.map(x=>x.day)),entries=CET4_DAYS.flatMap(d=>d.words.map(w=>({w,day:d.day}))),wrong=[];entries.forEach(({w,day})=>{const p=progress.words[key(w)];if(!p)return;if(!('inWrongBook'in p)&&p.wrong>p.right){p.inWrongBook=true;p.wrongReviewCount=0}if(p.inWrongBook&&!p.wrongDay)p.wrongDay=day;if(p.inWrongBook&&dueSet.has(p.wrongDay))wrong.push(w)});const uniqueWrong=[...new Map(wrong.map(w=>[key(w),w])).values()],box=$('#dailyDays');box.innerHTML='';due.forEach(item=>{const b=document.createElement('button');b.className='day';b.innerHTML=`Day ${item.day}<small>${item.overdue?'补第':'第'}${item.gap}天复习</small>`;b.onclick=()=>openDay(item.day,item.gap);box.appendChild(b)});if(uniqueWrong.length){const b=document.createElement('button');b.className='day';b.innerHTML=`错词<small>${uniqueWrong.length}词</small>`;b.onclick=()=>openWrongReview(uniqueWrong,'今日错词');box.appendChild(b)}$('#dailyEmpty').classList.toggle('hidden',due.length+uniqueWrong.length>0);$('#dailyDate').textContent=`${t} · 新学 ${nextDay?'Day '+nextDay.day:'已完成'} · 复习 ${due.length} 个 Day`;save();show('daily')}
function wrongWords(){const entries=CET4_DAYS.flatMap(d=>d.words.map(w=>({w,day:d.day}))),map=new Map;entries.forEach(({w,day})=>{const p=progress.words[key(w)];if(!p)return;if(!('inWrongBook'in p)&&p.wrong>p.right){p.inWrongBook=true;p.wrongReviewCount=0;p.wrongDay=day}if(p.inWrongBook&&!map.has(key(w)))map.set(key(w),w)});return [...map.values()]}
function showWrongBook(){const words=wrongWords(),box=$('#wrongWordList');box.innerHTML='';allMeaningsOpen=false;$('#toggleAllMeanings').textContent='👁 显示全部';words.forEach(w=>{const p=progress.words[key(w)],row=document.createElement('div');row.className='word-row';const en=document.createElement('div');en.className='word-en';en.innerHTML=`${w.word}<div class="review-note">Day ${p.wrongDay||'—'} · 正确复习 ${p.wrongReviewCount||0}/3</div>`;const cover=document.createElement('button');cover.className='meaning-cover';cover.textContent='点击查看';cover.dataset.open='0';cover.dataset.meaning=w.meaning;cover.onclick=()=>{const open=cover.dataset.open==='1';cover.dataset.open=open?'0':'1';cover.classList.toggle('revealed',!open);cover.textContent=open?'点击查看':w.meaning};row.append(en,cover);box.appendChild(row)});$('#wrongEmpty').classList.toggle('hidden',words.length>0);save();show('wrongbook')}
function toggleAllMeanings(){allMeaningsOpen=!allMeaningsOpen;$$('#wrongWordList .meaning-cover').forEach(cover=>{cover.dataset.open=allMeaningsOpen?'1':'0';cover.classList.toggle('revealed',allMeaningsOpen);cover.textContent=allMeaningsOpen?cover.dataset.meaning:'点击查看'});$('#toggleAllMeanings').textContent=allMeaningsOpen?'🙈 隐藏全部':'👁 显示全部'}
$$('.mode').forEach(b=>b.onclick=()=>start(b.dataset.mode,state.customWords));$$('[data-back]').forEach(b=>b.onclick=()=>show(b.dataset.back));$('#randomDay').onclick=dailyTask;$('#summaryHome').onclick=()=>show('home');$('#quit').onclick=()=>show('setup');$('#wrongBook').onclick=showWrongBook;$('#toggleAllMeanings').onclick=toggleAllMeanings;
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});setDailyQuote();renderDays();
